// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StellarElysium.Infrastructure.Persistence;

#nullable disable

namespace StellarElysium.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260211182432_InitialDesejos")]
    partial class InitialDesejos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StellarElysium.Domain.Entities.ContaGenshin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apelido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Servidor")
                        .HasColumnType("int");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("ContasGenshin");
                });

            modelBuilder.Entity("StellarElysium.Domain.Entities.Desejo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContaGenshinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraDesejo")
                        .HasColumnType("datetime2");

                    b.Property<string>("IdDesejoExterno")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NomeItem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Rareza")
                        .HasColumnType("int");

                    b.Property<int>("TipoBanner")
                        .HasColumnType("int");

                    b.Property<int>("TipoItem")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ContaGenshinId", "IdDesejoExterno")
                        .IsUnique();

                    b.HasIndex("ContaGenshinId", "TipoBanner", "DataHoraDesejo");

                    b.ToTable("Desejos");
                });

            modelBuilder.Entity("StellarElysium.Domain.Entities.Desejo", b =>
                {
                    b.HasOne("StellarElysium.Domain.Entities.ContaGenshin", "ContaGenshin")
                        .WithMany("Desejos")
                        .HasForeignKey("ContaGenshinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaGenshin");
                });

            modelBuilder.Entity("StellarElysium.Domain.Entities.ContaGenshin", b =>
                {
                    b.Navigation("Desejos");
                });
#pragma warning restore 612, 618
        }
    }
}
