// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StellarElysium.Infrastructure.Persistence;

#nullable disable

namespace StellarElysium.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StellarElysium.Domain.Entities.ContaGenshin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apelido")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("Servidor")
                        .HasColumnType("int");

                    b.Property<string>("Uid")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Uid", "Servidor")
                        .IsUnique();

                    b.ToTable("ContasGenshin");
                });

            modelBuilder.Entity("StellarElysium.Domain.Entities.Desejo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ContaGenshinId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataHoraDesejo")
                        .HasColumnType("datetime2");

                    b.Property<int>("GachaType")
                        .HasColumnType("int");

                    b.Property<string>("ItemId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("NomeItem")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PullId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("RankType")
                        .HasColumnType("int");

                    b.Property<string>("TipoItem")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("ContaGenshinId", "PullId")
                        .IsUnique();

                    b.HasIndex("ContaGenshinId", "GachaType", "DataHoraDesejo");

                    b.ToTable("Desejos");
                });

            modelBuilder.Entity("StellarElysium.Domain.Entities.Desejo", b =>
                {
                    b.HasOne("StellarElysium.Domain.Entities.ContaGenshin", "ContaGenshin")
                        .WithMany("Desejos")
                        .HasForeignKey("ContaGenshinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContaGenshin");
                });

            modelBuilder.Entity("StellarElysium.Domain.Entities.ContaGenshin", b =>
                {
                    b.Navigation("Desejos");
                });
#pragma warning restore 612, 618
        }
    }
}
