version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: stellar-elysium-sqlserver
    ports:
      - "1435:1433"
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "${SQLSERVER_SA_PASSWORD}"
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
